spring:
  profiles:
    active: @package.environment@
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.shuhistory.entity

pagehelper:
  helperDialect: mysql
  #  默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）。
  pageSizeZero: true
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。  reasonable: false
  supportMethodsArguments: true

knife4j:
  enable: true
  basic:
    enable: true
    username: shu
    password: shu100
  setting:
    enableDynamicParameter: true