spring:
  profiles:
    active: @package.environment@
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.shuhistory.entity

pagehelper:
  helperDialect: mysql
  #  默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）。
  pageSizeZero: true
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。  reasonable: false
  supportMethodsArguments: true

knife4j:
  enable: true
  basic:
    enable: true
    username: shu
    password: shu100
  setting:
    enableDynamicParameter: true


# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tEuURBDSoYv1Ew1vpTb # 访问身份验证中用到用户标识
    accessKeySecret: j83ESTEIjIXcRx5CniEhi8sU8aVO7S # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: todolist0522 # oss的存储空间
    dir:
      prefix: todolist2023/ # 上传文件夹路径前缀